ext {
    solr = [
            version: [
                    major: 2,
                    minor: 0,
                    rev: '6'
            ],
            flavor: 'solr6'
    ]
    alfrescoimage ='docker.io/xenit/alfresco-repository-community:6.2'
    tests = true
}
dependencies {
    runtime "org.alfresco:alfresco-search-services:2.0.6@zip"
}
