sudo: required
dist: trusty
services:
  - docker

language: java
jdk: oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
env:
  global:
    - DOCKER_USER=xenitpublisher
    - secure: "vEbluU4aeOP8I9Hby7rfl4I1zRjMD8Fr61XWTQiCpc+hy4DVoNEITLRQ+PqOf1m4y1UJSBgXahqucbQNlizDQUO+1k8xUkZy54E5XWaoOBQGxUyGRiIsei6XWqUpzH75/BMtbLhHtq0HhvdvN7hkW/XlVYMavITzMvJLGpt3AH2jNqUF4aVzEeuroBS8nKQ0JAfepX+pc1R//V9LEq5B62b/zPnKjRg4Jt/mKY8mXS2U7XQUSUOZCO9sKwyvQIGSLWBVZ1RN9KL0dRoY1qc5ZQBmM/AEqFmU9PRv3XBmM9vVpAEbVTvBFXnqNxxvroHThiyw6ISqnLq7wWLnmre01aA98Yp+oCYS65Q0oX7WJwpmjtM4Bx4EY0ShTaNszh4WnqSyyLHjhnFkWv+oNMX6UmWd9zt7cJVjcfot+94Y01S+y/HGZYHUJDuHpUxGtziriaKyAiBNKdUBhUCLzIz4fQBNFqNv1fDC8koCpLQNyzRtF1EjLRU66aVOiIO/3PmiepQwfkCsGLV2tzWpDcK1Yv+9dtNJlfHet6Yr1qIRsHn+TT34ndp1stcnJkMuElhokkFRiUEgLtaTTvZ+ZOU2O4dhO8pr7HBPLQM8BVENNr+/DUSrhpeWAczEcuxut8d486I7hro9/C/hSpnnVbDywWHn+auEy9hfmRYBkoCLlGM="
  matrix:
    - VERSIONS_TO_BUILD=solr1
    - VERSIONS_TO_BUILD=solr4
    - VERSIONS_TO_BUILD=solr6

script: ./gradlew -PrepoName=docker.io/xenit integrationTests --info

deploy:
  provider: script
  script: ./gradlew -PrepoName=docker.io/xenit pushDockerImage
  on:
    branch: master
