version: '3'

services:
  alfresco:
    image: ${ALFRESCO_IMAGE}
    restart: unless-stopped
    ports:
    - 8080
    environment:
    - SOLR_HOST=solr1
    - INDEX
    - SOLR_SSL=none
    - GLOBAL_alfresco.cluster.enabled=true
    - GLOBAL_solr.useDynamicShardRegistration=true
