version: '3'

services:
  solr1:
    image: ${DOCKER_IMAGE}
    restart: unless-stopped
    ports:
    - 8080
    hostname: solr1
    environment:
    - ALFRESCO_SSL=none
    - SOLR_HOST=solr1
    - ARCHIVE_ENABLE_ALFRESCO_TRACKING=false
    - ARCHIVE_INDEX_CONTENT=false
    - ALFRESCO_INDEX_CONTENT=false
    - MAX_HTTP_HEADER_SIZE=65536
    - CORES_ALFRESCO=alfresco-0;alfresco-1
    - GLOBAL_ALL_shard.method=DB_ID
    - GLOBAL_ALL_shard.count=3
    - GLOBAL_alfresco-0_shard.instance=0
    - GLOBAL_alfresco-1_shard.instance=1

  solr2:
    image: ${DOCKER_IMAGE}
    restart: unless-stopped
    ports:
    - 8080
    hostname: solr2
    environment:
    - ALFRESCO_SSL=none
    - SOLR_HOST=solr2
    - ARCHIVE_ENABLE_ALFRESCO_TRACKING=false
    - ARCHIVE_INDEX_CONTENT=false
    - ALFRESCO_INDEX_CONTENT=false
    - MAX_HTTP_HEADER_SIZE=65536
    - CORES_ALFRESCO=alfresco-2
    - GLOBAL_ALL_shard.method=DB_ID
    - GLOBAL_ALL_shard.count=3    
    - GLOBAL_alfresco-2_shard.instance=2