version: '3'

services:
  alfresco:
    image: ${ALFRESCO_IMAGE}
    container_name: alfresco
    restart: unless-stopped
    ports:
    - 8080
    environment:
    - SOLR_HOST=solr1
    - INDEX
    - SOLR_SSL=none
    - ENABLE_CLUSTERING=true
    - DYNAMIC_SHARD_REGISTRATION=true    
