plugins {
    id 'java-library'
}

description = "Xenit backup"
group = 'eu.xenit.solr-backup'

java {
    // Runs inside built images, so this should be 11
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
    withJavadocJar()
    withSourcesJar()
}


dependencies {
    // compile against solr6 libraries
    compileOnly("org.apache.solr:solr-core:${solrVersion}") {
        exclude group: 'org.restlet.jee' // Only available in JCenter, not essential in this project.
    }
    compileOnly "org.alfresco:alfresco-search:${assVersion}"

    implementation platform("com.amazonaws:aws-java-sdk-bom:${amazonVersion}")

    implementation('com.amazonaws:aws-java-sdk-core')
    implementation('com.amazonaws:aws-java-sdk-s3')
    implementation("com.amazonaws:aws-java-sdk-sts")
    testImplementation("org.apache.solr:solr-core:${solrVersion}") {
        exclude group: 'org.restlet.jee' // Only available in JCenter, not essential in this project.
    }
    testImplementation "org.alfresco:alfresco-search:${assVersion}"

    testImplementation platform("org.junit:junit-bom:${junitJupiterVersion}")

    testImplementation "org.junit.jupiter:junit-jupiter"
    testRuntimeOnly    "org.junit.jupiter:junit-jupiter-engine"
    testRuntimeOnly    "org.junit.platform:junit-platform-launcher"

    testImplementation "org.mockito:mockito-core:${mockitoVersion}"
    testImplementation "org.mockito:mockito-junit-jupiter:${mockitoVersion}"

}