ext {
    solr = [
            version: [
                    major: 1,
                    minor: 4,
                    rev: '3.4'
            ],
            flavor: 'solr6'
    ]
    alfrescoimage ='docker.io/xenit/alfresco-repository-community:6.1.2-ga'
    tests = true
}
dependencies {
    runtime "org.alfresco:alfresco-search-services:1.4.3.4@zip"
}
